import { DC } from "../../constants";

export const glitchSpeedUpgrades = [
  {
    name: "The power is growing",
    id: 1,
    cost: new Decimal("1e400"),
    requirement: "Reality with all 9 effects active",
    ReqBits: () => 511,
    hasFailed: () => !(Glitch.activeAugments.length < 9),
    checkRequirement: () => Glitch.isRunning && Glitch.activeAugments.length >= 9,
    checkEvent: GAME_EVENT.REALITY_RESET_BEFORE,
    description: "Some Celestial Reality's effect that nerf Prestige gain are weakened by 25%",
    effect: () =>  1.25,
  },
  {
    name: "The cycle continues",
    id: 2,
    cost: new Decimal("1e400"),
    requirement: () => `Have ${format("e6e11")} Antimatter with first 9 effects`,
    ReqBits: () => 511,
    hasFailed: () => !(Glitch.activeAugments.length < 10),
    checkRequirement: () => Glitch.isRunning && Glitch.activeAugments.length >= 9 && Currency.antimatter.gte("e6e11"),
    checkEvent: GAME_EVENT.GAME_TICK_AFTER,
    description: () => `Ra's static tickspeed is raised by 1.1 per AG past ${format(1e4)}, RG is 1.03 per past ${format(1e4)}, TG is 1.005 per past ${format(1e4)}`,
    effect: () =>  Decimal.pow(1.1, player.galaxies.sub(1e4).max(0)).mul( Decimal.pow(1.03, Replicanti.galaxies.total.sub(1e4).max(0))).mul( Decimal.pow(1.005, player.dilation.totalTachyonGalaxies.sub(1e4).max(0))).max(1),
    formatEffect: value => formatX(value, 2, 2)
  },
  {
    name: "Around and around",
    id: 3,
    cost: new Decimal("1e400"),
    requirement: () => `Have less than ${format("e1e9")} Antimatter after 5 seconds in this Infinity with all 10 effects and Continuum active`,
    ReqBits: () => 1023,
    hasFailed: () => !(Glitch.augmentEffectBits == 1023) || !Laitela.continuumActive,
    checkRequirement: () => Glitch.isRunning && Glitch.augmentEffectBits == 1023 && Time.thisInfinityRealTime.totalSeconds.gte(5) && Laitela.continuumActive && Currency.antimatter.lt("1e1E9"),
    checkEvent: GAME_EVENT.GAME_TICK_AFTER,
    description: "The Rift Force formula is changed to log10(value) ^ 0.2, also you can charge one Infinity Upgrade in Glitch's Reality",
  },
  {
    name: "Unlimited Dimensions",
    id: 4,
    cost: new Decimal("1e550"),
    requirement: () => `Reach ${format("1e69000")} Eternity Points with a negative Blackhole of ${format("e1e9")} with the first 9 effects`,
    ReqBits: () => 511,
    hasFailed: () => !(Glitch.augmentEffectBits == 511),
    checkRequirement: () => Glitch.isRunning && Glitch.augmentEffectBits == 511 && player.requirementChecks.reality.slowestBH.gte('e1e9') && Currency.eternityPoints.gte("1e69000"),
    checkEvent: GAME_EVENT.GAME_TICK_AFTER,
    description: "Unlock Chaos Dimensions",
  },
  {
    name: "Dilemma",
    id: 5,
    cost: new Decimal("1e1500"),
    requirement: () => `Reach ${format('e4e25')} Antimatter`,
    ReqBits: () => 0,
    hasFailed: () => Glitch.augmentEffectBits != 0,
    checkRequirement: () => Glitch.isRunning && Glitch.augmentEffectBits == 0 && Currency.antimatter.gt("e4e25"),
    checkEvent: GAME_EVENT.GAME_TICK_AFTER,
    description: "Chaos Dimensions multiplier based on Rift Force",
    effect: () =>  Currency.riftForce.value.add(2).log(2).pow(0.5),
    formatEffect: value => formatX(value, 2, 2)
  },
  {
    name: "Polar",
    id: 6,
    cost: new Decimal("1e2000"),
    requirement: () => `Reach ${format('e3e9')} Infinity Points with the first 9 effects`,
    ReqBits: () => 511,
    hasFailed: () => !(Glitch.augmentEffectBits == 511),
    checkRequirement: () => Glitch.isRunning && Glitch.augmentEffectBits == 511 && Currency.infinityPoints.value.gt('e3e9'),
    checkEvent: GAME_EVENT.GAME_TICK_AFTER,
    description: "Challenger Essence muliplier based on Rift force",
    effect: () =>  Currency.riftForce.value.add(14).log(14).pow(0.8),
    formatEffect: value => formatX(value, 2, 2)
  },
  {
    name: "Not a lot",
    id: 7,
    cost: new Decimal("1e5000"),
    requirement: () => `Reach a ${formatPercents(1.5e4)} Galaxy strength from Chaos Cores`,
    ReqBits: () => 0,
    hasFailed: () => false,
    checkRequirement: () => Glitch.chaosCoresBoost.gt(1.5e4),
    checkEvent: GAME_EVENT.GAME_TICK_AFTER,
    description: "The first Chaos Dimension gains a multiplier based on Challenger Essence",
    effect: () =>  Currency.challengersEssence.value.add(1).pow(3),
    formatEffect: value => formatX(value, 2, 2)
  },
  {
    name: "A waist of time",
    id: 8,
    cost: new Decimal("1e32000"),
    requirement: () => `Reach ${format(1e3)} Glitch Glyph Sacrifice`,
    ReqBits: () => 511,
    hasFailed: () => false,
    checkRequirement: () => player.reality.glyphs.sac.glitch.gte(1e3),
    checkEvent: GAME_EVENT.GAME_TICK_AFTER,
    description: "Glitch Glyph Sacrifice scales with Chaos Cores",
    effect: () =>  Currency.chaosCores.value.add(1.1).log(1.1).pow(1.5),
    formatEffect: value => formatX(value, 2, 2)
  },
];
