
export const ChallengerUpgrades = [
  {
    name: "A broken chain",
    id: 0,
    cost: new Decimal(1),
    description: "All Infinity and Break Infinity upgrades can be brought while Doomed",
  },
  {
    name: "Fairly earned",
    id: 1,
    cost: new Decimal(3),
    description: "All achievements are enabled while Doomed",
  },
  {
    name: "Unblock knowledge",
    id: 2,
    cost: new Decimal(3),
    description: "All Time Studies are effective while Doomed",
  },
  {
    name: "Forever real",
    id: 3,
    cost: new Decimal(8),
    description: "All Reality upgrades are enabled while Doomed",
  },
  {
    name: "Permanently",
    id: 4,
    cost: new Decimal(18),
    description: "All perks are enabled while Doomed",
  },
  {
    name: "Gone for miles",
    id: 5,
    cost: new Decimal(7),
    description: "All Eternity Milestones can be unlocked while Doomed",
  },
  {
    name: "Rereset",
    id: 6,
    cost: new Decimal(3),
    description: "Infinty and Eternity multipliers are enabled while Doomed",
  },
  {
    name: "Multiplicitvity",
    id: 7,
    cost: new Decimal(15),
    description: "IP and EP multipliers are enabled while Doomed",
  },
  {
    name: "Automating automation",
    id: 8,
    cost: new Decimal(10),
    description: "Unlock autobuyers for Pelle upgrades and The Galaxy Generator",
  },
  {
    name: "Delivered dilation",
    id: 9,
    cost: new Decimal(20),
    description: "All Dilation upgrades can be brought while Doomed",
  },
  {
    name: "Bugged Glitch",
    id: 10,
    cost: new Decimal(15),
    description: "All Glitch's challenges are active while Doomed",
  },
  {
    name: "Al-chemical",
    id: 11,
    cost: new Decimal(17),
    description: "Alchemy does not reset and is active while Doomed",
  },
  {
    name: "Teresa",
    id: 12,
    cost: new Decimal(13),
    description: "All Teresa unlocks are active while Doomed",
  },
  {
    name: "Effarig",
    id: 13,
    cost: new Decimal(6),
    description: "All Effarig unlocks are active while Doomed",
  },
  {
    name: "Nameless",
    id: 14,
    cost: new Decimal(8),
    description: "All Nameless unlocks are active while Doomed and enable the Black Hole",
  },
  {
    name: "V",
    id: 15,
    cost: new Decimal(18),
    description: "All V unlocks are active while Doomed",
  },
  {
    name: "Ra",
    id: 16,
    cost: new Decimal(33),
    description: "All Ra unlocks are active while Doomed",
  },
  {
    name: "Laitela",
    id: 17,
    cost: new Decimal(60),
    description: "All Laitela unlocks are active while Doomed",
  },
  {
    name: "IMAGINATION",
    id: 18,
    cost: new Decimal(50),
    description: "All Imaginary upgrades are active while Doomed",
  },
  {
    name: "Rift apart",
    id: 19,
    cost: new Decimal(23),
    description: "All Rifts are faster and auto filled without draining resorces",
  },
  {
    name: "Fragments",
    id: 20,
    cost: new Decimal(12),
    description: "Gain 100% of Remnants per-second",
  },
  {
    name: "Ancient Enchntments",
    id: 21,
    cost: new Decimal(7),
    description: "All glyphs effect are enabled while doomed, Effarig, Reality and Cursed have unique effects",
  },
];
