
export const preInfinityUG = [
  {
    name: "Dimless",
    id: 0,
    requirement: () => `Reach ${format(1e15)} Antimatter without any Dimension Boosts, no galaxies (pre-Infinity)`,
    hasFailed: () => false,
    checkRequirement: () => player.antimatter.e >= 15,
    progLock: () => player.dimensionBoosts != 0 || player.galaxies > 0 || PlayerProgress.infinityUnlocked(),
    checkEvent: GAME_EVENT.GAME_TICK_BEFORE,
    description: "AD multiplier from Dimension Boosts",
    effect: () => 1 + player.dimensionBoosts / 4,
    formatEffect: value => formatX(value, 2, 2),
  },
  {
  name: "Dimensional Limits",
    id: 1,
    requirement: () => `Have ${format(1e25)} Antimatter with only one Dimension Boost, no Galaxies (pre-Infinity)`,
    hasFailed: () => false,
    checkRequirement: () => player.antimatter.e >= 25,
    progLock: () => player.dimensionBoosts > 1 || player.galaxies > 0 || PlayerProgress.infinityUnlocked(),
    checkEvent: GAME_EVENT.GAME_TICK_BEFORE,
    description: "AD multiplier from Tickspeed purchases",
    effect: () => 1 + Tickspeed.totalForEffect / 15,
    formatEffect: value => formatX(value, 2, 2)
  },
  {
  name: "Vector 2",
    id: 2,
    requirement: () => `Have ${format(1e35)} Antimatter with upto two Dimension Boosts, no galaxies (pre-Infinity)`,
    hasFailed: () => false,
    checkRequirement: () => player.antimatter.e >= 35,
    progLock: () => player.dimensionBoosts > 2 || player.galaxies > 0 || PlayerProgress.infinityUnlocked(),
    checkEvent: GAME_EVENT.GAME_TICK_BEFORE,
    description: "25x AD multiplier oscillating over 10 seconds",
    effect: () => Math.max(Math.abs(Math.sin(player.records.realTimePlayed /10000) ) * 25,1),
    formatEffect: value => formatX(value, 2, 2)
  },
  {
    name: "8th Dimensional",
    id: 3,
    requirement: () => `Have ${format(1e50)} Antimatter with upto four Dimension Boosts, no Galaxies and only one of each Dimension tier brought (pre-Infinity)`,
    hasFailed: () => AntimatterDimensions.all.some(ad => ad.bought > 1),
    checkRequirement: () => player.antimatter.e >= 50 && AntimatterDimensions.all.some(ad => ad.bought < 2),
    progLock: () => player.dimensionBoosts > 4 || player.galaxies > 0 || PlayerProgress.infinityUnlocked(),
    checkEvent: GAME_EVENT.GAME_TICK_BEFORE,
    description: "1st ADs multiplier by the amount of 8th ADs",
    effect: () => Decimal.pow(1.1, AntimatterDimension(8).totalAmount.div(10)).add(1),
    formatEffect: value => formatX(value, 2, 2)
  },
  {
    name: "Galactic Inforcement",
    id: 4,
    requirement: () => `Have ${format(1e7)} Antimatter with no Dimension Boosts, one Galaxy, up to ten 2nd Dimensions (pre-Infinity)`,
    hasFailed: () => AntimatterDimension(2).amount.gt(10),
    checkRequirement: () => player.antimatter.e >= 7 && AntimatterDimension(2).amount.lte(10),
    progLock: () => player.dimensionBoosts > 0 || player.galaxies > 1 || PlayerProgress.infinityUnlocked(),
    checkEvent: GAME_EVENT.GAME_TICK_BEFORE,
    description: "Additional Tickspeed purchases based on their amount",
    effect: () => Math.floor(Math.log2(Tickspeed.totalForEffect + 2) ** 2) - 1,
    formatEffect: value => "+" + formatInt(value)
  },
  {
    name: "Galactic Limitation",
    id: 5,
    requirement: () => `Have ${format(1e25)} Antimatter with no Dimension Boosts, one Galaxy, up to 20 4th Dimensions (pre-Infinity)`,
    hasFailed: () => AntimatterDimension(4).amount.gt(20),
    checkRequirement: () => player.antimatter.e >= 25 && AntimatterDimension(4).amount.lte(20),
    progLock: () => player.galaxies > 1 || player.dimensionBoosts > 0 || PlayerProgress.infinityUnlocked(),
    checkEvent: GAME_EVENT.GAME_TICK_BEFORE,
    description: "Additional Tickspeed purchases based on Dimension Boosts and Galaxies",
    effect: () => Math.floor(Math.log2(player.dimensionBoosts * player.galaxies + 1) ** 1.75),
    formatEffect: value => "+" + formatInt(value)
  },
  {
    name: "Galactic Capacity",
    id: 6,
    requirement: () => `Reach ${format(Number.MAX_VALUE, 2)} Antimatter with only one Antimatter Galaxy (pre-Infinity)`,
    hasFailed: () => false,
    checkRequirement: () => player.antimatter.gt(1.79e308),
    progLock: () => player.galaxies > 1 || PlayerProgress.infinityUnlocked(),
    checkEvent: GAME_EVENT.GAME_TICK_BEFORE,
    description: "Double infinity point gain",
    effect: () => 2,
    formatEffect: value => formatX(value, 2, 2)
  },
  {
    name: "Galactic Instance",
    id: 7,
    requirement: () => `Have ${format(3)} Antimatter Galaxies without Infinity broken (pre-Break)`,
    hasFailed: () => false,
    checkRequirement: () => player.galaxies >= 3,
    progLock: () => PlayerProgress.hasBroken(),
    checkEvent: GAME_EVENT.GAME_TICK_BEFORE,
    description: "Triple infinity point gain",
    effect: () => 3,
    formatEffect: value => formatX(value, 2, 2)
  },
  
];
